// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RsaProject.DbContexts;

namespace RsaProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RsaProject.Model.Bom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParentNode")
                        .HasColumnType("int");

                    b.Property<bool>("isHead")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Bom");
                });

            modelBuilder.Entity("RsaProject.Model.BomDetail", b =>
                {
                    b.Property<string>("BomCode")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("ChildMaterialCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("MaterialNum")
                        .HasColumnType("int");

                    b.HasKey("BomCode");

                    b.ToTable("BomDetail");
                });

            modelBuilder.Entity("RsaProject.Model.BomHead", b =>
                {
                    b.Property<string>("BomCode")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("MaterialCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("BomCode");

                    b.HasIndex("BomCode")
                        .IsUnique();

                    b.ToTable("BomHead");
                });

            modelBuilder.Entity("RsaProject.Model.BomDetail", b =>
                {
                    b.HasOne("RsaProject.Model.BomHead", null)
                        .WithMany("BomDetail")
                        .HasForeignKey("BomCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
